tt

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -429,7 +429,7 @@ jobs:
             then
             exit 0
               else
-              exit 0
+              exit 1
              fi
 
       - run:
@@ -438,6 +438,12 @@ jobs:
             # your code here 
             URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
             curl -s ${URL} | grep "Welcome"
+            then
+             # Change this to 0 after the job fails
+               return 1
+            else
+             return 1
+             fi
 
       # Here's where you will add some code to rollback on failure
       - destroy-environment:
@@ -499,7 +505,8 @@ jobs:
           command: |
             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
             then
-              # your code here
+
+            fi
             fi
             
 workflows:
