tt

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -396,60 +396,49 @@ jobs:
 
   smoke-test:
     docker:
-      # Lightweight Docker image 
-      - image: python:3.10-alpine3.16
+      - image: circleci/node:13.8.0 
     steps:
-      # Checkout code from git
-      - checkout 
+
+      - checkout
+      - install_awscli
+      - install_nodejs
 
       - run:
           name: Install dependencies
           command: |
             # your code here
-            apk add --update --no-cache curl aws-cli tar gzip nodejs npm
-
-      - attach_workspace:
-          at: ~/
-
-      - run:
-          name: Get backend url
-          command: |
-            # your code here
+            sudo apt install -y curl
+            sudo apt install net-tools
       - run:
           name: Backend smoke test.
           command: |
-            # your code here
+
             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
             --query 'Reservations[*].Instances[*].PublicIpAddress' \
             --output text)
-
+            
             export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+            echo "${BACKEND_PUBLIC_IP}"
             if curl -s $API_URL/api/status | grep "ok"
             then
-            exit 0
-              else
-              exit 0
-             fi
-
+                exit 0
+            else
+                exit 1
+            fi
       - run:
           name: Frontend smoke test.
           command: |
-            # your code here 
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-            curl -s ${URL} | grep "Welcome"
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
             then
-             # Change this to 0 after the job fails
-               return 0
+              # This is the intentional error, if "Welcome" is indeed in the response this step will exit with exit code 1
+              exit 0
             else
-             return 1
-             fi
-
-      # Here's where you will add some code to rollback on failure
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-      - revert-migrations:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}  
+              exit 1
+            fi
+      # # - destroy-environment
+      ## - revert-migrations
 
   cloudfront-update:
     docker:
